Repository WildCodeSchool-2023-09/remfr-php-p3-afac974, pull requests merged in 2024-01, with the labels that each got.

#14 page artists + separation des mentions légales et a propos
  src/Controller/HomeController.php
  templates/home/aboutUs.html.twig
  templates/home/artists.html.twig
  templates/home/mentions.html.twig
  templates/include/_footer.html.twig
Labels: conflicts

#17 Navbar footer
  templates/include/_navbar.html.twig
Labels: enhancement, invalid

#18 added missing informations
  templates/artwork/artwork.html.twig
Labels: Reviewers missing

#21 Custom form theme
  assets/styles/app.scss
  assets/styles/global.scss
  config/packages/twig.yaml
  migrations/Version20231222100524.php
  migrations/Version20240104091250.php
  migrations/Version20240109101511.php
  migrations/Version20240109144945.php
  src/Controller/ArtworkController.php
  src/Entity/Artwork.php
  src/Form/ArtworkType.php
  templates/artwork/new.html.twig
  templates/form/custom_theme.html.twig
  templates/include/_navbar.html.twig
Labels: Reviewers missing, help wanted

#23 U1.4 ter
  src/Controller/LoginController.php
  templates/base.html.twig
  templates/home/index.html.twig
  templates/security/login.html.twig
Labels: Reviewers missing

#34 Favorites
  assets/images/not_favorite.svg
  config/packages/vich_uploader.yaml
  migrations/Version20240123164016.php
  migrations/Version20240124134200.php
  phpmd.xml
  src/Controller/AdminController.php
  src/Controller/ArtworkController.php
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/ArtworkFixtures.php
  src/DataFixtures/TypeFixtures.php
  src/Entity/Artwork.php
  src/Entity/User.php
  templates/admin/edit_artwork.html.twig
  templates/admin/index.html.twig
  templates/admin/show_artworks.html.twig
  templates/artwork/artwork.html.twig
  templates/artwork/edit_artwork_artist.html.twig
  templates/artwork/new.html.twig
  templates/artwork/show_artworks_artist.html.twig
  templates/include/_navbar.html.twig
  templates/user/favorite_gallery.html.twig
Labels: Reviewers missing

#37 Fix divers
  README.md
  migrations/Version20240124170406.php
  src/Controller/AdminController.php
  src/DataFixtures/ArtworkFixtures.php
  src/DataFixtures/TypeFixtures.php
  src/Entity/Artwork.php
  src/Entity/Type.php
  templates/admin/index.html.twig
  templates/artwork/artwork.html.twig
  templates/artwork/new.html.twig
  templates/home/index.html.twig
  templates/include/_navbar.html.twig
  templates/security/login.html.twig
  templates/user/favorite_gallery.html.twig
  templates/user/show.html.twig
Labels: enhancement
